# Generated by Django 6.0.2 on 2026-02-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="base_cost",
            new_name="budget",
        ),
        migrations.RemoveField(
            model_name="event",
            name="cost_per_guest",
        ),
        migrations.AddField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("WEDDING", "Wedding"),
                    ("SWEET16", "Sweet 16"),
                    ("QUINCE", "Quinceañera"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
    ]
