# Generated by Django 6.0.2 on 2026-02-05 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_base_cost_event_budget_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("WEDDING", "Wedding"),
                    ("SWEET16", "Sweet 16"),
                    ("QUINCE", "Quinceanera"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
    ]
