# Generated by Django 6.0.2 on 2026-02-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_event_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="bust",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Bust measurement (inches)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="hips",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Hips measurement (inches)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("VIP", "VIP"),
                    ("INACTIVE", "Inactive"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="waist",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Waist measurement (inches)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("DRESS", "Dress"),
                    ("SHOES", "Shoes"),
                    ("ACCESSORY", "Accessory"),
                    ("LINENS", "Linens"),
                    ("CHAIR_COVER", "Chair Cover"),
                    ("TABLECLOTH", "Tablecloth"),
                    ("FURNITURE", "Furniture"),
                    ("DECOR", "Other Decor (Vase, etc.)"),
                ],
                default="DRESS",
                max_length=20,
            ),
        ),
    ]
