# Generated by Django 6.0.2 on 2026-02-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_customer_birthday_customer_bust_customer_hips_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="deposit_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="event",
            name="deposit_returned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rental",
            name="deposit_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="rental",
            name="deposit_returned",
            field=models.BooleanField(default=False),
        ),
    ]
